rootProject.name = 'demo'

include 'application', 'persistence', 'domainmodel', 'domainservices', 'web'

project(':application').projectDir = file('submodules/application')
project(':domainmodel').projectDir = file('submodules/domainmodel')
project(':persistence').projectDir = file('submodules/persistence')
project(':domainservices').projectDir = file('submodules/domainservices')
project(':web').projectDir = file('submodules/web')
